### PR TITLE
log redaction for rocksdb (SERVER-24991)

### PR DESCRIPTION
**Pull request by igorsol**
(cherry picked from commit 0043c942537a11bd9d28c390d6866dc1504092b8)

### CODE REVIEW

**Comment by igorcanadi** [comment]
See my comments on original PR: https://github.com/percona/mongo-rocks/pull/30

**Comment by igorsol** [comment]
@igorcanadi you are right, redaction of thread names and prefixes is redundant
I updated this PR:
- redaction of thread names removed
- redaction of prfixes removed

**Comment by igorcanadi** [comment]
Just realized I forgot to merge this, sorry about that! You should have pinged me :)

**Comment by igorsol** [comment]
Thank you!

**Pull request merged**
